# FireFly Signer Configuration
# https://github.com/hyperledger/firefly-signer
server:
  address: "0.0.0.0"
  port: 8545

log:
  level: debug

backend:
  url: "http://besu:8545"
  chainId: 1991

fileWallet:
  path: "/keys"
  filenames:
    with0xPrefix: true
    primaryExt: ".key"
    passwordTrimSpace: true
  defaultPasswordFile: "/keys/password.txt"
